version: '3'
services:
  elasticsearch:
    image: elastic/elasticsearch:8.13.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: elastic/logstash:8.13.0
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf  # Replace with your logstash.conf path
    depends_on:
      - elasticsearch

  filebeat:
    image: elastic/filebeat:8.13.0
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml  # Replace with your filebeat.yml path
    depends_on:
      - logstash

networks:
  elk:

volumes:
  elasticsearch-data:

