version: '3'
services:

  downloader:
    build: ./
    ports:
      - "9040:9040"
    volumes:
      - ./logs:/app/log/ 

  elasticsearch:
    image: elastic/elasticsearch:8.13.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: elastic/logstash:8.13.0
    container_name: logstash
    command: ["bin/logstash", "-f", "/usr/share/logstash/config/logstash.conf"]
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
    depends_on:
      - elasticsearch

  filebeat:
    image: elastic/filebeat:8.13.0
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml 
      - ./logs:/var/log/ 
    depends_on:
      - logstash

volumes:
  elasticsearch-data:

